url: http://elektret.github.io
title: A personal Blog
subtitle: A blogging framework for hackers.
author: Manuel
description:
date_format: "ordinal"
subscribe_rss: /atom.xml
subscribe_email:
email:
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygment
paginate: 5
paginate_path: "blog/posts/:num"
recent_posts: 5
excerpt_link: "Read on &rarr;"
excerpt_separator: "<!--more-->"
titlecase: true
default_asides: []
